### ISSUE TITLE
codeofconduct file added

### ISSUE THREAD

**Issue by pinak22dhir** [Tech-Emcees/NoteX#20]
can u assign this to me?

**Comment by TeeWrath** [comment]
@pinak22dhir Hey, have you joined the NoteX discord server. If not please join, we would love to have a chat with you on this issue. 
link  - https://discord.gg/Xgx2y7H8uE
Kindly introduce yourself there and take the developer role. Then we can have discussion about your issue in the notex-app-discussion channel.
Excited to see your contributions.

**Comment by pinak22dhir** [comment]
sure @TeeWrath assign this issue to me so that i can commit further contributions

**Comment by TeeWrath** [comment]
@pinak22dhir this issue has been assigned to you.

**Comment by pinak22dhir** [comment]
sir it is not showing assigned option?

**Comment by TeeWrath** [comment]
check now, and no need to call me sir. We're of same age group

**Comment by pinak22dhir** [comment]
yes @TeeWrath now showing, thanks

**Comment by pinak22dhir** [comment]
resolved issue#20

**Comment by pinak22dhir** [comment]
@bhaskar1001101  kindly add kwoc tag on the issue
