### ISSUE TITLE
[Bug] Typo error in the README.md file.

### ISSUE THREAD

**Issue by nepalivai** [Tech-Emcees/NoteX#23]
## Description
Found a few grammatical errors in the README.md file.

## Steps To Reproduce
1. Go to 'README.md file'.
3. Scroll down to 'Contribution Guidelines'.
4. See error (one of many).

## Expected Behavior
Period should be added after all the sentence ending.

## Screenshots
<img width="479" alt="image" src="https://github.com/The-NoteX/NoteX/assets/108126089/2ac5f4c9-f1bf-41fe-b986-375916e9f26d">

**Comment by MiirzaBaig** [comment]
can I work on this/

**Comment by bhaskar1001101** [comment]
@I-MirzaBaig This issue already has a merged PR linked to it. 
Closing this issue.
