### ISSUE TITLE
Web version of NoteX

### ISSUE THREAD

**Issue by Rukkya** [Tech-Emcees/NoteX#27]
**Feat**:

Making web version of NoteX for different devices.

**Comment by RJ-04** [comment]
> making NoteX accessible through web browsers as well.

I have assigned this issue to you .

**Comment by TeeWrath** [comment]
@Rukkya Hey there, we understand you are enthusiastic about the web version for NoteX, however , our current concern and focus is on the software at hand, which requires great amount of work yet. Hence we are unlikely to proceed with this issue at the moment. Thank you. We look forward to see your contributions.
Regards,
Team NoteX

**Comment by Rukkya** [comment]
OK so which technical issues / additives  are you considering for the
moment so I can work on one of them?
